name: CI/CD Pipeline for AskRC

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Check out code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      #  Get the pip cache directory
      - name: Get cache dir 
        id: pip-cache-dir
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      
      # Cache pip dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir}}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Login to Azure CLI
      - name: Azure Login
        uses: azure/login@v1
        with:
          credentials_json: '${{ secrets.AZURE_SECRETS }}'

      # # Deploy to Azure
      # - name: Deploy to Azure Function
      #   run: |
      #     az functionapp deployment source config-zip \
      #       -g RESOURCE_GROUP_NAME \
      #       -n FUNCTION_APP_NAME \
      #       --src-path /path/to/deployment.zip
          

      # Run the RAG Chatbot App (if required post-deployment)
      - name: Run the AskRC Application
        run: |
          streamlit run app.py --server.headless true
