name: Python Tests

on:
  push:
    branches:
      - main  # Run tests on pushes to the main branch
  pull_request:
    branches:
      - main  # Run tests on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run tests
      run: |
        pytest Testing/testcase_1.py
        pytest Testing/testcase_2.py
        pytest Testing/testcase_3.py
